CREATE TABLE IF NOT EXISTS FAKECORE;

DROP TABLE IF EXISTS ALUMNO;
CREATE TABLE IF NOT EXISTS ALUMNO(
    ID_ALUMNO INT NOT NULL UNIQUE,
    NOMBRES VARCHAR(50) NOT NULL,
    APELLIDO_PATERNO VARCHAR(50) NOT NULL,
    APELLIDO_MATERNO VARCHAR(50) NOT NULL,
    CARRERA VARCHAR(50) NOT NULL,
    GRADO INT NOT NULL,
    PRIMARY KEY(ID_ALUMNO)
);