USE FAKECORE;

INSERT INTO ALUMNO VALUES(1000, 'Joel', 'Rueda', 'Robles');
INSERT INTO ALUMNO(NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO) VALUES
    (1294' Chester', 'Smith', 'Wong'),
    (1351' Jack', 'Watts', 'Simmons'),
    (1133' Larry', 'Fleming', 'Mack'),
    (1797' Betty', 'Thornton', 'Cain'),
    (1431' Nellie', 'Cook', 'Jones'),
    (1304' Cecelia', 'Ballard', 'Greer'),
    (1212' Justin', 'Fitzgerald', 'Martin'),
    (1326' Angel', 'Doyle', 'Casey'),
    (1181' Jesse', 'Davidson', 'Strickland'),
    (1298' Marcus', 'Norman', 'Evans'),
    (1345' John', 'McKenzie', 'Pope'),
    (1927' Gussie', 'Stanley', 'Gross'),
    (1132' Mathilda', 'Alvarez', 'Massey'),
    (1591' Viola', 'Wise', 'Barnett'),
    (1040' Laura', 'Swanson', 'Lynch'),
    (1400' Ola', 'Roy', 'Ford'),
    (1905' Lina', 'Richards', 'Barrett'),
    (1194' Annie', 'Gilbert', 'Hopkins'),
    (1971' Alberta', 'Larson', 'Bell'),
    (1144' Jose', 'Briggs', 'Hill'),
    (1562' Caleb', 'Matthews', 'Silva'),
    (1882' Ronald', 'Harrison', 'Leonard'),
    (1688' Nina', 'Walton', 'Pena'),
    (1033' Emma', 'Roberson', 'Hart'),
    (1622' Luke', 'Roberts', 'Guerrero'),
    (1333' Mabel', 'Horton', 'Turner'),
    (1678' Carlos', 'Allison', 'Gordon'),
    (1274' Earl', 'Briggs', 'Herrera'),
    (1363' Nellie', 'May', 'Harmon'),
    (1380' Seth', 'Alexander', 'Quinn'),
    (1489' Martin', 'Miles', 'Douglas'),
    (1689' Clayton', 'Bridges', 'Cox'),
    (1869' Gordon', 'Johnson', 'Benson')
;

INSERT INTO MAESTRO VALUES(5000, 'Payne', 'Hart', 'Hunter');
INSERT INTO MAESTRO(NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO) VALUES
    (5699' Rodney', 'Hall', 'Yates'),
    (5778' Virgie', 'Page', 'Walker'),
    (5262' Christina', 'Bass', 'Morales'),
    (5245' Devin', 'Armstrong', 'Houston'),
    (5739' Roger', 'Foster', 'Caldwell'),
    (5801' Cory', 'Thornton', 'Campbell'),
    (5406' Myrtle', 'Rowe', 'Ryan'),
    (5274' Joseph', 'Carr', 'Boone'),
    (5006' Jose', 'Greene', 'Fletcher'),
    (5828' Tony', 'Ellis', 'Harrison'),
    (5256' Nancy', 'Robbins', 'Gordon'),
    (5369' Mary', 'Craig', 'Guzman'),
    (5916' Katie', 'Douglas', 'Hernandez'),
    (5956' Fanny', 'Lamb', 'Russell'),
    (5358' Sarah', 'Baker', 'Olson'),
    (5184' Carrie', 'Butler', 'Black'),
    (5090' Louise', 'Alexander', 'Gibson'),
    (5471' Miguel', 'Carlson', 'Chavez'),
    (5228' Carrie', 'Robbins', 'Hernandez'),
    (5548' Isabel', 'Norton', 'Mack'),
    (5437' Lily', 'Harvey', 'Weber'),
    (5223' Dean', 'Turner', 'Owen'),
    (5830' Effie', 'Reid', 'Nguyen'),
    (5473' Hettie', 'Salazar', 'Obrien'),
    (5113' Shane', 'Carpenter', 'Robbins'),
    (5418' Phoebe', 'Gardner', 'Johnson')
;